replicaCount: 2
image:
  repository: registry.example.com/toto/k8s-proxy-image-swapper
  pullPolicy: IfNotPresent
  tag: "v0.3.0"

config: |
  port: 8443
  tlskeypath: "/tls/key.pem"
  tlscertpath: "/tls/cert.pem"

securityContext:
 #capabilities:
 #  drop:
 #  - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

enableDebug: false

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

# You can obtain this value the following way :
# kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
# Note that this doesn't work on k3s since CAs are used differently. You need to
# use the CA base64 in /var/lib/rancher/k3s/server/tls/server-ca.crt
caBundle: {}
# This must be resolvable from inside the cluster (on the nodes)
registryUrl: docker-registry-internal.example.com
